### PR TITLE
Update python-ci.yaml

### PR DESCRIPTION
**Pull request by ChrisMcCarthyDev**

### CODE REVIEW

**Review by czar-ec-envitia — COMMENTED** [review]
~~This would only run on main and dev branches, we may need to define one for branches that are neither, so that we can check if our PRs pass tests and can be built~~

nevermind, just saw `pull_request:
    branches: [main, dev]`

**Review by czar-ec-envitia — COMMENTED** [review]
`runs-on: ubuntu-latest`
checks only linux environment, do we want to do something similar to check yt on windows and mac os?

**Review by Rumbelows — DISMISSED** [review]

**Comment by ChrisMcCarthyDev** [comment]
Damn this very quick change from GitHub actions page got messy. Had to pull down the branch and remove the auto creation of platform dirs in the setup.py script. To be fair it probably for the best. Importing the YT package from the YT setup.py, even if it is in a post-install script, it's best to not have setup.py touch any of the package you're installing. Anyway, this works for now and goes one step further than our current TeamCity pipeline as this is checking against Python versions 3.8, 3.9, and 3.10, whereas TeamCity was only checking on Python 3.8.

**Comment by ChrisMcCarthyDev** [comment]
> `runs-on: ubuntu-latest` checks only linux environment, do we want to do something similar to check yt on windows and mac os?

Yes for Linux and Windows. So the idea is still to have everything running in TeamCity, as we already have both a Linux and Windows VM on AWS linked to TeamCity. But while there's issues with the TeamCity instance, we can use GitHub actions rather than having builds blocked.

**Review by Rumbelows — APPROVED** [review]

**Pull request merged**
